### PR TITLE
Generalized Interface for SourceControl Integrations

### PR DESCRIPTION
**Pull request by robertDurst**
See discussion here: https://github.com/wondrous-dev/wondrous-frontend/pull/39

Addresses: 
* https://github.com/wondrous-dev/source-control-integrations/issues/1

### CODE REVIEW

**Comment by robertDurst** [comment]
@terryli0095 @andywong418 basically where I left off before, but has:
* GUID for id's
* some super #sexy GitHub action CI stuff

**Comment by robertDurst** [comment]
Should be GTG.

**Comment by andywong418** [comment]
This looks awesome - what do we think of https://github.com/wondrous-dev/wondrous-frontend/pull/39/files#r757916817. At what layer do we understand what source control system we are using?

**Comment by robertDurst** [comment]
> what layer do we understand what source control system we are using

I think ideally, we never have to?

**Comment by robertDurst** [comment]
Missed a few comments from there. Adding:
* source type 
* statusEnum

**Comment by robertDurst** [comment]
Added as per last commit.

**Review by andywong418 — APPROVED** [review]
Looks awesome!

**Pull request merged**
