### PR TITLE
Remove GUID in favor of Source Control's Own ID

### PR DESCRIPTION
**Pull request by robertDurst**
Extended to take in an array of strings in order to be able to deterministically recreate the same objects using the unique identifier system of the source. I.E. for GitHub, projects are identified by "ORG_NAME/REPO_NAME". Thus, two of objects which have the same "ORG_NAME/REPO_NAME" should be equal.

### CODE REVIEW

**Comment by andywong418** [comment]
Is the thinking behind this that we would use this projectID with the type of source control we use - wondering if there is a unique identifier from Github/Gitlab we could use instead?

**Comment by saihaj** [comment]
> wondering if there is a unique identifier from Github/Gitlab we could use instead?

For GitHub there is ID on node https://docs.github.com/en/graphql/reference/queries#node which is a relay complaint ID https://relay.dev/graphql/objectidentification.htm

**Review by saihaj — COMMENTED** [review]
If we are going to store this in our DB we will have a unique ID for each entry? So do we need this? Other thing is underlying datasource will also come with an unique identifier (which is unique to them). Don’t think I understand purpose and advantage we get of doing ID generation ourselves 😅

**Comment by robertDurst** [comment]
Sure, we can pull out this id and use whatever GitHub/BitBucket gives us.

GitHub: https://docs.github.com/en/rest/reference/pulls#list-pull-requests
BitBucket: https://developer.atlassian.com/server/bitbucket/how-tos/command-line-rest/

I must have missed this in the initial scan of the docs.

**Comment by robertDurst** [comment]
> Don’t think I understand purpose and advantage we get of doing ID generation ourselves 😅

None - missed the existence of the unique ID. Believe I assumed this was id per project/org, not globally unique... the example given in the docs is `1` which seemed very odd.

> If we are going to store this in our DB we will have a unique ID for each entry? So do we need this?

Yes? We need a way to identify objects from GitHub so when we sync everything up we can see what has changed and what has not and furthermore when we "write" back to GitHub we need to know which entity we are updating.

**Comment by robertDurst** [comment]
Thanks for the feedback @andywong418 and @saihaj . Updated the PR by removing GUID since we can just pull the ID from the source control mechanism itself.

**Review by saihaj — APPROVED** [review]

**Pull request merged**
